export const H2H_CONFIG = {
  PICKS_PER_USER: 6,
  TEAMS_PER_USER: 3,
  WIN_POINTS: 20,
  TIE_POINTS: 10,
  LOSS_POINTS: 0,
  DRAFT_OPEN_HOURS_BEFORE: 72,
  DRAFT_CLOSE_HOURS_BEFORE: 24,
  SCORING_BUFFER_DAYS: 1,
  VALID_EVENT_TYPES: [0, 1, 2, 3, 4, 5],
};
